### ISSUE TITLE
Re-factor bin/testplan and test result setting/ manual runner into App::ape

### ISSUE THREAD

**Issue by teodesian** [teodesian/App-Prove-Elasticsearch#40]
I've been calling it A::P::E for a while, may as well make it official so we can have a cute little logo, goes with the whole troglodyne theme too

e.g. 

`ape plan ...`
`ape test ...`

**Comment by troglodyne** [comment]
:D

**Comment by teodesian** [comment]
ape plan
ape test
ape update
